
development:
  adapter: postgresql
  encoding: unicode
  database: homerkr_development
  pool: 5
  host: localhost
  username: strivedi
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: homerkr_test
  pool: 5
  host: localhost
  username: strivedi
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: homerkr_production
  pool: 5
  host: localhost
  username: strivedi
  password:
